version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "localhost:http://host.docker.internal:8545"
      GRAPH_LOG: info
      ETHEREUM_POLLING_INTERVAL: 1000
      ETHEREUM_REORG_THRESHOLD: 1
      RUST_BACKTRACE: full

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    platform: linux/amd64
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
